package enums;

public enum ConfigProperties {
    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOT,
    SKIPEDSTEPSSCREENSHOT,
    RETRYFAILEDTESTS,
    BROWSER,
    RUNMODE,
    USERNAME,
    PASSWORD,
    USER
}
